<?php
require_once __DIR__ . '/includes/functions.php';

$pageTitle    = 'Dashboard';
$pageSubtitle = date('l, j F');
$activeNav    = 'dashboard';

$today        = get_today_stats();
$week         = get_week_stats();
$monthly      = get_monthly_stats();
$quarterly    = get_quarterly_stats();
$heatmap      = get_activity_heatmap();
$distribution = get_subject_distribution();
$neglected    = get_neglected_subjects(5);
$recent       = get_recent_cycles(8);
$goal         = get_active_goal('daily');
$weeklyGoal   = get_active_goal('weekly');
$streak       = get_streak();

$goalTarget = $goal['target_cycles'] ?? 4;
$goalPct    = $goalTarget > 0 ? min(100, round(($today['completed_cycles'] / $goalTarget) * 100)) : 0;

$extraScripts = [
    'assets/js/chart.umd.min.js',   // local copy — CDN was returning 404
    'assets/js/dashboard.js',
];
require __DIR__ . '/includes/header.php';
?>

<section class="hero">
  <div>
    <div class="hero-figure">
      <span class="big num" id="hero-completed"><?= (int)$today['completed_cycles'] ?></span>
      <span class="of">of <?= (int)$goalTarget ?> cycles</span>
    </div>
    <div class="hero-label">Today's ledger &middot; goal <span id="hero-goal-pct"><?= $goalPct ?></span>% filled</div>
    <div class="bar-track" style="width:220px; margin-top:10px;">
      <div class="bar-fill" id="hero-bar" style="width:<?= $goalPct ?>%;"></div>
    </div>
  </div>

  <div class="hero-stats">
    <div class="hero-stat">
      <div class="v amber num" id="hero-study"><?= minutes_to_hm((int)$today['total_study_minutes']) ?></div>
      <div class="l">Studied today</div>
    </div>
    <div class="hero-stat">
      <div class="v teal num" id="hero-revision"><?= minutes_to_hm((int)$today['total_revision_minutes']) ?></div>
      <div class="l">Revised today</div>
    </div>
    <div class="hero-stat">
      <div class="v num" id="hero-streak"><?= (int)$streak['current_streak'] ?></div>
      <div class="l">Day streak</div>
    </div>
    <div class="hero-stat">
      <div class="v num" id="hero-subjects"><?= (int)$today['subjects_touched'] ?></div>
      <div class="l">Subjects touched</div>
    </div>
  </div>
</section>

<!-- LeetCode-style Activity Matrix / Heatmap -->
<div class="panel heatmap-panel mt-4">
  <div class="panel-head panel-head-wrap">
    <div class="heatmap-head-left">
      <div class="heatmap-title-row">
        <svg class="heatmap-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
          <line x1="16" y1="2" x2="16" y2="6"></line>
          <line x1="8" y1="2" x2="8" y2="6"></line>
          <line x1="3" y1="10" x2="21" y2="10"></line>
        </svg>
        <h2>Study Activity</h2>
        <span class="badge badge-teal badge-sm">Activity Matrix</span>
      </div>
      <span class="hint" id="heatmap-hint">
        <strong id="heatmap-active-days" class="num"><?= (int)$heatmap['summary']['total_active_days'] ?></strong> active days &middot; 
        <strong id="heatmap-cycles-count" class="num"><?= (int)$heatmap['summary']['total_completed_cycles'] ?></strong> cycles &middot; 
        <strong id="heatmap-total-hours" class="num"><?= (float)$heatmap['summary']['total_hours'] ?></strong>h logged in the past year
      </span>
    </div>
    <div class="heatmap-controls">
      <div class="heatmap-streaks">
        <div class="streak-pill" title="Longest historical streak">
          <span class="muted">Max:</span>
          <strong class="num" id="heatmap-max-streak"><?= (int)$streak['longest_streak'] ?>d</strong>
        </div>
        <div class="streak-pill active" title="Current ongoing streak">
          <span class="muted">Current:</span>
          <strong class="num" id="heatmap-cur-streak"><?= (int)$streak['current_streak'] ?>d</strong>
        </div>
      </div>
      <div class="select-wrap">
        <select id="heatmap-year-select" class="btn-select" aria-label="Select year for study heatmap">
          <option value="">Last 12 Months</option>
          <?php foreach ($heatmap['available_years'] as $yr): ?>
            <option value="<?= (int)$yr ?>"><?= (int)$yr ?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </div>
  </div>

  <div class="heatmap-scroll-area">
    <div class="heatmap-wrapper" id="heatmap-matrix">
      <!-- Generated by JS renderHeatmap() -->
    </div>
  </div>

  <div class="heatmap-footer">
    <div class="heatmap-legend">
      <span class="legend-label">Less</span>
      <span class="heat-swatch level-0" title="0 minutes"></span>
      <span class="heat-swatch level-1" title="1 – 59 minutes"></span>
      <span class="heat-swatch level-2" title="1h – 2h"></span>
      <span class="heat-swatch level-3" title="2h – 3h"></span>
      <span class="heat-swatch level-4" title="3h+ marathon"></span>
      <span class="legend-label">More</span>
    </div>
    <div class="heatmap-footnote muted">
      Tip: Click any square to view its subject breakdown
    </div>
  </div>
</div>

<div class="grid grid-main mt-4">

  <div class="panel" id="panel-study-overview">
    <div class="panel-head panel-head-wrap">
      <div class="panel-title-tabs">
        <div class="tab-pill-group" role="tablist" aria-label="Study view options">
          <button type="button" class="tab-pill active" id="tab-monthly" role="tab" aria-selected="true" aria-controls="view-monthly-wrap">Monthly</button>
          <button type="button" class="tab-pill" id="tab-quarterly" role="tab" aria-selected="false" aria-controls="view-quarterly-wrap">Quarterly</button>
        </div>
        <span class="hint" id="study-panel-hint"><?= date('F Y', strtotime($monthly['month'] . '-01')) ?> &middot; cumulative hours</span>
      </div>

      <div class="month-nav" id="monthly-controls">
        <button type="button" class="btn btn-ghost btn-icon" id="month-prev" title="Previous month" aria-label="Previous month">&lsaquo;</button>
        <input type="month" id="month-picker" value="<?= htmlspecialchars($monthly['month']) ?>" max="<?= date('Y-m') ?>">
        <button type="button" class="btn btn-ghost btn-icon" id="month-next" title="Next month" aria-label="Next month">&rsaquo;</button>
      </div>

      <div class="quarter-nav" id="quarterly-controls" style="display:none;">
        <button type="button" class="btn btn-ghost btn-icon" id="quarter-prev" title="Previous year" aria-label="Previous year">&lsaquo;</button>
        <span class="quarter-year-display num font-bold" id="quarter-year-display"><?= (int)$quarterly['year'] ?></span>
        <button type="button" class="btn btn-ghost btn-icon" id="quarter-next" title="Next year" aria-label="Next year">&rsaquo;</button>
      </div>
    </div>

    <!-- Monthly View -->
    <div id="view-monthly-wrap">
      <canvas id="chart-monthly" height="180"></canvas>
    </div>

    <!-- Quarterly View with attractive Bar Chart -->
    <div id="view-quarterly-wrap" style="display:none;">
      <div class="quarterly-cards-grid" id="quarterly-cards-container">
        <!-- Rendered by JS -->
      </div>
      <div class="quarterly-chart-wrap">
        <canvas id="chart-quarterly" height="180"></canvas>
      </div>
      <div class="quarterly-summary-strip" id="quarterly-summary-strip">
        <!-- Annual totals & best quarter badge -->
      </div>
    </div>

    <div id="day-breakdown" class="day-breakdown" hidden></div>
  </div>

  <div class="panel">
    <div class="panel-head">
      <h2>Subject progress</h2>
      <span class="hint">most time invested first</span>
    </div>
    <div class="progress-list" id="subject-progress-rows">
      <?php if (empty($distribution)): ?>
        <div class="empty" style="padding: 32px 12px;">
          <p>Complete a cycle and this fills in on its own.</p>
        </div>
      <?php else: ?>
        <?php $maxMinutes = max(array_column($distribution, 'total_minutes')); ?>
        <?php foreach ($distribution as $d): ?>
          <div class="progress-row subject-progress-row" data-subject-id="<?= (int)$d['id'] ?>" tabindex="0" role="button" aria-expanded="false">
            <div class="progress-row-top">
              <span class="dot" style="background:<?= htmlspecialchars($d['color_hex']) ?>;"></span>
              <span class="progress-row-name"><?= htmlspecialchars($d['name']) ?></span>
              <span class="progress-row-value num" data-minutes="<?= (int)$d['total_minutes'] ?>"><?= minutes_to_hm((int)$d['total_minutes']) ?></span>
              <button type="button" class="subject-delete" data-subject-id="<?= (int)$d['id'] ?>" title="Delete subject" aria-label="Delete this subject">Delete</button>
            </div>
            <div class="bar-track">
              <div class="bar-fill" style="width:<?= $maxMinutes > 0 ? round($d['total_minutes'] / $maxMinutes * 100) : 0 ?>%; background:<?= htmlspecialchars($d['color_hex']) ?>;"></div>
            </div>
            <div class="material-progress-list" data-materials-for="<?= (int)$d['id'] ?>" hidden></div>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>
    </div>
  </div>
</div>

<div class="grid grid-2 mt-4">

  <div class="panel">
    <div class="panel-head">
      <h2>Neglected subjects</h2>
      <span class="hint">longest since last touched</span>
    </div>
    <div class="rows" id="neglected-rows">
      <?php if (empty($neglected)): ?>
        <div class="empty"><p>Add a subject to start tracking neglect.</p></div>
      <?php else: foreach ($neglected as $i => $n): ?>
        <div class="row">
          <span class="row-rank num"><?= $i + 1 ?></span>
          <span class="row-title"><?= htmlspecialchars($n['name']) ?></span>
          <span class="row-value">
            <?= $n['last_studied_at'] ? ((int)$n['days_since_studied']) . ' days' : 'never studied' ?>
          </span>
        </div>
      <?php endforeach; endif; ?>
    </div>
  </div>

  <div class="panel">
    <div class="panel-head">
      <h2>Goal progress</h2>
      <span class="hint">daily &amp; weekly</span>
    </div>

    <div class="goal-block">
      <div class="goal-block-head">
        <span class="goal-block-label">Daily goal</span>
      </div>
      <?php if (!$goal): ?>
        <div class="empty" style="padding: 16px 2px;">
          <p>Set a daily cycle target on the Goals page.</p>
          <a href="goals.php" class="btn btn-primary mt-4" style="display:inline-flex;">Set a goal</a>
        </div>
      <?php else: ?>
        <div class="row-sub" style="margin-bottom:8px;" id="daily-goal-cycles-label">
          <?= (int)$today['completed_cycles'] ?> of <?= (int)$goal['target_cycles'] ?> cycles completed today
        </div>
        <div class="bar-track"><div class="bar-fill" id="daily-goal-cycles-bar" style="width:<?= $goalPct ?>%;"></div></div>
        <?php if ($goal['target_minutes']): ?>
          <div class="row-sub" style="margin-top:14px; margin-bottom:8px;" id="daily-goal-minutes-label">
            <?= minutes_to_hm((int)$today['total_minutes']) ?> of <?= minutes_to_hm((int)$goal['target_minutes']) ?> minutes
          </div>
          <div class="bar-track"><div class="bar-fill teal" id="daily-goal-minutes-bar" style="width:<?= min(100, round($today['total_minutes'] / $goal['target_minutes'] * 100)) ?>%;"></div></div>
        <?php endif; ?>
      <?php endif; ?>
    </div>

    <div class="goal-block goal-block-divider">
      <div class="goal-block-head">
        <span class="goal-block-label">Weekly goal</span>
      </div>
      <?php if (!$weeklyGoal): ?>
        <div class="empty" style="padding: 16px 2px;">
          <p>Set a weekly cycle target on the Goals page.</p>
          <a href="goals.php" class="btn btn-secondary mt-4" style="display:inline-flex;">Set a goal</a>
        </div>
      <?php else:
        $weekCyclePct = $weeklyGoal['target_cycles'] > 0 ? min(100, round($week['completed_cycles'] / $weeklyGoal['target_cycles'] * 100)) : 0;
      ?>
        <div class="row-sub" style="margin-bottom:8px;" id="weekly-goal-cycles-label">
          <?= (int)$week['completed_cycles'] ?> of <?= (int)$weeklyGoal['target_cycles'] ?> cycles completed this week
        </div>
        <div class="bar-track"><div class="bar-fill teal" id="weekly-goal-cycles-bar" style="width:<?= $weekCyclePct ?>%;"></div></div>
        <?php if ($weeklyGoal['target_minutes']): ?>
          <div class="row-sub" style="margin-top:14px; margin-bottom:8px;" id="weekly-goal-minutes-label">
            <?= minutes_to_hm((int)$week['total_minutes']) ?> of <?= minutes_to_hm((int)$weeklyGoal['target_minutes']) ?> minutes
          </div>
          <div class="bar-track"><div class="bar-fill" id="weekly-goal-minutes-bar" style="width:<?= min(100, round($week['total_minutes'] / $weeklyGoal['target_minutes'] * 100)) ?>%;"></div></div>
        <?php endif; ?>
      <?php endif; ?>
    </div>
  </div>
</div>

<div class="panel mt-4">
  <div class="panel-head">
    <h2>Recent cycles</h2>
    <span class="hint"><?= count($recent) ?> shown</span>
  </div>
  <?php if (empty($recent)): ?>
    <div class="empty">
      <h3>No cycles yet</h3>
      <p>Start your first study cycle and it will show up here the moment you complete it.</p>
    </div>
  <?php else: ?>
  <div class="table-scroll">
  <table id="recent-table">
    <thead>
      <tr><th>Subject</th><th>Material</th><th>Date</th><th>Study</th><th>Revision</th><th>Status</th></tr>
    </thead>
    <tbody>
      <?php foreach ($recent as $c): ?>
        <tr>
          <td data-label="Subject"><span class="dot" style="background:<?= htmlspecialchars($c['color_hex']) ?>; display:inline-block; margin-right:8px;"></span><?= htmlspecialchars($c['subject_name']) ?></td>
          <td class="muted" data-label="Material"><?= htmlspecialchars($c['material_title'] ?? '—') ?></td>
          <td class="muted" data-label="Date"><?= friendly_date($c['cycle_date']) ?></td>
          <td class="num" data-label="Study"><?= (int)$c['study_minutes'] ?>m</td>
          <td class="num" data-label="Revision"><?= (int)$c['revision_minutes'] ?>m</td>
          <td data-label="Status">
            <?php if ($c['status'] === 'completed'): ?><span class="badge badge-amber">completed</span>
            <?php elseif ($c['status'] === 'in_progress'): ?><span class="badge badge-teal">in progress</span>
            <?php else: ?><span class="badge badge-muted">abandoned</span><?php endif; ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  </div>
  <?php endif; ?>
</div>

<script>
  window.__DASHBOARD__ = {
    monthly: <?= json_encode($monthly) ?>,
    quarterly: <?= json_encode($quarterly) ?>,
    heatmap: <?= json_encode($heatmap) ?>,
    distribution: <?= json_encode($distribution) ?>,
    goalTarget: <?= json_encode((int)$goalTarget) ?>,
    weeklyGoalTarget: <?= json_encode($weeklyGoal ? (int)$weeklyGoal['target_cycles'] : null) ?>
  };
</script>

<?php require __DIR__ . '/includes/footer.php'; ?>
